version: '3.9'
services:

  redis:
    image: redis:7.0.10-alpine
    expose:
      - 6379
  
  web:
    build: ./client/
    ports:
      - "5000:5000"

  api:
    build: .
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - redis
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
volumes:
  dependencies:

