class Users {
  constructor(uid, email, displayName) {
    this.uid = uid; // represents the id generated by the firestore
    this.email = email;
    this.displayName = displayName;
  }
}

module.exports = Users;
